# Generated by Django 6.0.1 on 2026-04-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='message',
            new_name='content',
        ),
    ]
