# Generated by Django 6.0.1 on 2026-04-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0002_rename_message_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
