# Generated by Django 5.2.8 on 2026-01-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_message_alter_posts_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
